on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of the release"
        required: true

name: Upload Release Asset

jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-24.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binaries
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -v -x -trimpath -o "upload-linux-arm"
          CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -v -x -trimpath -o "upload-android-arm64"

      - name: Upload release artifacts
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises;
            const { repo: { owner, repo } } = context;

            // Directly access the tag from the input parameter
            const tag = '${{ github.event.inputs.tag }}';  // Use GitHub context for tag input

            if (!tag) {
              throw new Error('No tag provided');
            }

            // Get the release by tag
            const release = await github.repos.getReleaseByTag({
              owner,
              repo,
              tag
            });

            console.log('Release:', release);

            // Upload assets
            for (let file of await fs.readdir(".")) {
              if (!file.startsWith("upload-")) continue;
              console.log("Uploading", file);
              await github.repos.uploadReleaseAsset({
                owner,
                repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(file),
              });
            }
