on:
  release:
    types: [published]
  workflow_dispatch: # This enables manual trigger

name: Upload Release Asset
jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-24.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build binaries
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -v -x -trimpath -o "upload-linux-arm"
          CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -v -x -trimpath -o "upload-android-arm64"
      - name: Upload release artifacts
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs").promises;
            const { repo: { owner, repo }, sha } = context;

            const release = await github.repos.getReleaseByTag({
              owner, repo,
              tag: process.env.GITHUB_REF.replace("refs/tags/", ""),
            });
            console.log("Release:", { release });

            for (let file of await fs.readdir(".")) {
              if (!file.startsWith("upload-")) continue;
              console.log("Uploading", file);
              await github.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(file),
              });
            }
